### PR TITLE
Fix molecule test

### PR DESCRIPTION
**Pull request by l00ptr**

### CODE REVIEW

**Comment by l00ptr** [comment]
Hi,

It's ready for a review, let me know if it's usefull or not and also what i need to change before merging this :)

Best regards,

**Comment by l00ptr** [comment]
FYI i would like to fix the CI (at least with Debian Buster) before proposing more pull request.

**Review by santiagomr — APPROVED** [review]
Hi @l00ptr, thank you for these changes and improvements.

While the role still maintains full support for Stretch and Bullseye (in addition to Buster, of course), it is better to leave the molecule scenarios as you propose than to let the tests continue to give a false failure on Stretch because of the docker image.

**Comment by santiagomr** [comment]
Thanks Julian, I have already accepted and merged the changes before doing a squash via CLI.

GitHub doesn't seem to detect these types of merges correctly. I close the PR but your changes were accepted as proposed.

We look forward to your next PR.

Regards

**Pull request closed without merging**
